services:
  # --- Service 1: LaTeX CV Generator ---
  - name: latex-cv-generator
    type: web
    plan: free
    env: docker # Ensure you have a Dockerfile in the specified rootDir
    # dockerfilePath: ./Dockerfile # Optional: Specify if not named Dockerfile
    # dockerContext: ./auth-backend/latex-cv-generator # Optional: Specify context path if needed
    branch: main
    rootDir: ./auth-backend/latex-cv-generator
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001 # Internal port your Docker container exposes

  # --- Service 2: Main Auth Backend ---
  - type: web
    name: auth-service
    env: node
    plan: free
    branch: main
    rootDir: ./auth-backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000 # Internal port your Node app listens on
      # Add other necessary env vars like DATABASE_URL, JWT_SECRET etc.

  # --- Service 3: Other Backend (Placeholder) ---
  # If you have another backend service, define it here.
  # Example:
  # - type: web
  #   name: other-backend
  #   env: node # Or python, etc.
  #   plan: free
  #   branch: main
  #   rootDir: ./other-backend-directory
  #   buildCommand: "npm install"
  #   startCommand: "npm start"
  #   envVars:
  #     - key: PORT
  #       value: 3002 # Use a different internal port

  # --- Service 4: Frontend ---
  - name: frontend
  type: web
  plan: free
  branch: main
  rootDir: ./frontend
  buildCommand: "npm install && npm run build"
  # Remove any runtime property that might be causing issues
  # Use environment variables properly
  distDir: ./dist
  # Add a start command to serve your static files
  startCommand: "npm run serve || npx serve -s dist"
  envVars:
    - key: REACT_APP_AUTH_API_URL
      # Replace fromService with direct value or use one of the valid properties
      value: "${auth-service.RENDER_EXTERNAL_URL}"
      # Alternative approach using valid fromService properties:
      # fromService:
      #   type: web
      #   name: auth-service
      #   property: host
    - key: REACT_APP_GENERATOR_API_URL
      value: "${latex-cv-generator.RENDER_EXTERNAL_URL}"
      # Alternative approach using valid fromService properties:
      # fromService:
      #   type: web
      #   name: latex-cv-generator
      #   property: host