services:
  # --- Service 1: LaTeX CV Generator ---
  - name: latex-cv-generator
    type: web
    plan: free
    env: docker # Ensure you have a Dockerfile in the specified rootDir
    # dockerfilePath: ./Dockerfile # Optional: Specify if not named Dockerfile
    # dockerContext: ./auth-backend/latex-cv-generator # Optional: Specify context path if needed
    branch: main
    rootDir: ./auth-backend/latex-cv-generator
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001 # Internal port your Docker container exposes

  # --- Service 2: Main Auth Backend ---
  - type: web
    name: auth-service
    env: node
    plan: free
    branch: main
    rootDir: ./auth-backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000 # Internal port your Node app listens on
      # Add other necessary env vars like DATABASE_URL, JWT_SECRET etc.

  # --- Service 3: Other Backend (Placeholder) ---
  # If you have another backend service, define it here.
  # Example:
  # - type: web
  #   name: other-backend
  #   env: node # Or python, etc.
  #   plan: free
  #   branch: main
  #   rootDir: ./other-backend-directory
  #   buildCommand: "npm install"
  #   startCommand: "npm start"
  #   envVars:
  #     - key: PORT
  #       value: 3002 # Use a different internal port

  # --- Service 4: Frontend ---
  - name: frontend
    type: web
    plan: free
    branch: main
    rootDir: ./frontend
    buildCommand: "npm install && npm run build"
    # For web type, use publishDir (or sometimes distDir)
    publishDir: ./dist # The folder containing the static build output
    # Alternative: try distDir if publishDir doesn't work
    # distDir: ./dist
    # You might need to add a start command for web service
    startCommand: "npm run serve" # Or another command that can serve your static files
    envVars:
      - key: REACT_APP_AUTH_API_URL
        fromService:
          type: web
          name: auth-service
          property: url
      - key: REACT_APP_GENERATOR_API_URL
        fromService:
          type: web
          name: latex-cv-generator
          property: url