# render.yaml (in the root of your repository)
services:
  # --- Service 1: LaTeX CV Generator ---
  - type: web
    name: latex-cv-generator
    env: node
    plan: free
    branch: main
    rootDir: ./auth-backend/latex-cv-generator
    aptPackages:
      - texlive-full
      - ghostscript
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001

  # --- Service 2: Main Auth Backend ---
  - type: web
    name: auth-service
    env: node
    plan: free
    branch: main
    rootDir: ./auth-backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  # --- Service 3: Other Backend ---
  - type: web
    name: other-backend
    env: node
    plan: free
    branch: main
    rootDir: ./auth-backend/other-backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002

  # --- Service 4: Frontend (Static Site) ---
  - type: static
    name: frontend
    plan: free
    branch: main
    rootDir: ./frontend
    buildCommand: "npm install && npm run build"
    publishDir: ./dist
    envVars:
      - key: REACT_APP_AUTH_API_URL
        fromService:
          type: web
          name: auth-service
          property: url
      - key: REACT_APP_OTHER_API_URL
        fromService:
          type: web
          name: other-backend
          property: url
      - key: REACT_APP_GENERATOR_API_URL
        fromService:
          type: web
          name: latex-cv-generator
          property: url
