services:
  - name: latex-cv-generator
    type: web
    plan: free
    env: docker
    branch: main
    rootDir: ./auth-backend/latex-cv-generator
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
  # --- Service 2: Main Auth Backend ---
  - type: web
    name: auth-service
    env: node
    plan: free
    branch: main
    rootDir: ./auth-backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

  # --- Service 3: Other Backend ---
  


  - name: frontend
  type: web
  plan: free
  branch: main
  rootDir: ./frontend
  buildCommand: "npm install && npm run build"
  # Remove the problematic publishDir line and replace with distDir
  distDir: ./dist
  envVars:
    - key: REACT_APP_AUTH_API_URL
      fromService:
        type: web
        name: auth-service
        property: url
    - key: REACT_APP_OTHER_API_URL
      fromService:
        type: web
        name: other-backend
        property: url
    - key: REACT_APP_GENERATOR_API_URL
      fromService:
        type: web
        name: latex-cv-generator
        property: url